[project]
name = "fundment-backend-interview-take-home"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "coverage>=7.10.4",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
]
